application: 
  port: 7979
database:
  host: "localhost"
  port: 5431
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url:"localhost"
  sender_email:"test@gmail.com"
  authorization_token:"my-secret-token"
